Catalog_of_things V.1 📦
gisachris/ruby-capstone-project pull request #49
Opened 2023-08-17 09:55 UTC by gisachris

## In this PR we present the `Catalog_Of_Things` Console Application For our Ruby Group Capstone Project 🧑‍🤝‍🧑:
**Below are all our implementation detail and information regarding our steps and approach to making this console application** 

## Requirements 📜 
- Create All `classes` 🏛️, `methods` :fishsticks:  & `properties` 🕸️ mentioned in this `UML` diagram [here](https://github.com/microverseinc/curriculum-ruby/blob/main/group-capstone/images/catalog_of_my_things.png)
- Create a `main.rb` file that will serve as your console app entry-point. 🚪
- Create a `schema.sql` file with tables that will be analogical to the structure of the `classes` in your app. 📅 
- Create Storage 🕳️ for all Entricable `data` into the application with abilities to `load` and `store` data. 
- Create a video presenting the features of the project you built. you can view it [here](url)
- Follow strict git flow 🌊 workflow to ensure clean `pair programming` and remote `code storage` 🏪 

## Achievements
- Create All `classes` 🏛️, `methods` :fishsticks:  & `properties` 🕸️ mentioned in this `UML` diagram [here](https://github.com/microverseinc/curriculum-ruby/blob/main/group-capstone/images/catalog_of_my_things.png) ✅ 
- Create a `main.rb` file that will serve as your console app entry-point. 🚪 ✅ 
- Create a `schema.sql` file with tables that will be analogical to the structure of the `classes` in your app. 📅  ✅ 
- Create Storage 🕳️ for all Entricable `data` into the application with abilities to `load` and `store` data. ✅ 
- Create a video presenting the features of the project you built. you can view it [here](url) ✅ 
- Follow strict git flow 🌊 workflow to ensure clean `pair programming` and remote `code storage` 🏪  ✅ 

## Team Note
This capstone project has been a thriller and exciting journey for all parties involved where we used all our skills to accomplish this project and we continue to do so until completion. Our team was complised of 3 individuals : @gisachris, @VaheStepanyan100 & @Enoisong so no implemenation for `movies` and `source` classes were made as per requirements [here](https://github.com/microverseinc/curriculum-ruby/blob/main/group-capstone/catalog_of_my_things_divided.md) 

**We would love to hear from you our CR 👨‍💻 about our implementation for this project 📦, any changes or improvements to the application would be highly appreciated. Thank you! 🤝**

2023-08-17 13:00 UTC, iambenkis requested changes
#### Hi Team ( @gisachris , @VaheStepanyan100 , @Enoisong )

Good job so far!
There are some issues that you still need to work on to prepare your project for the final evaluation but you are almost there!
You did a great job, keep up the good work 👍🏼

![giphy](https://user-images.githubusercontent.com/25227022/169391888-8dd8108f-0d42-4e54-87cc-a3f9fd392dbc.gif)


## Highlights

✔️ Preserving data 💯 
✔️ Database Schema 💯 
✔️ Tests perform professionally

## Suggested changes
_Check the comments under the review._

You can use as many of my suggestions as you want. If there is anything you would like to skip - feel free to do that. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2023-08-17 13:00 UTC, iambenkis commented on classes/item.rb
> +
- [ ] [**Optional**] You don't need to have `:source`  attribute since the team is made up of three people. Kindly remove this column and the  `:source` attribute.

2023-08-17 13:00 UTC, iambenkis commented on main.rb
> +    puts "5. - List all authors (e.g. 'Stephen King')"
- [ ]  [**Optional**] You don't need to have a source option since the team is made up of three people. Kindly remove this column and the source option.

2023-08-17 13:00 UTC, iambenkis commented on classes/item.rb
> +
- [ ] Good job creating your `Catalog of my things` project 👏 . You've done an amazing job on this one 👏 👏 . But I think there is one thing you have to implement. When you implemented the Inheritance, you should make sure that all the `Item` inherit all the methods found in the `Item` class. It means the `book` item 📖 , `game` item 🎮 , and `music` item 🎵 , should have an `author`, a `label`, and a `genre`.  

**Eg:**
A book could have a 
title: Lord's rings
author: Benjamin Kisenge
label color: blue
genre: fiction

2023-08-17 13:00 UTC, iambenkis commented on schema.sql
> +);
- [ ] You should  also  complete the foreign keys  in your schema so that each Item points to `label` , `genre`, and `author`
It will look like this :
```sql
CREATE TABLE books (
  id BIGSERIAL NOT NULL PRIMARY KEY,
  publisher VARCHAR(150) NOT NULL,
  cover_state VARCHAR(150) NOT NULL,
  genre_id INT NULL REFERENCES genres(id) ON DELETE CASCADE,  -- You should add for genre and author
  author_id INT NULL REFERENCES authors(id) ON DELETE CASCADE,
  label_id INT NULL REFERENCES labels(id) ON DELETE CASCADE, -- You have only this 
  publish_date DATE NOT NULL,
  archived BOOLEAN NOT NULL
);

```

2023-08-18 08:42 UTC, gisachris commented
## Required Changes Implementation 👨‍💻 
**Below are our implementations for the required changes**

## Requirements
- Remove the unneccesary `:source` attribute from our `Item` class
- Remove the unneccesary `:source` methods and display messages from our `app` & `main` files
- Implement required changes on specific tables in `Schema.sql` file
- Implement required changes in `Item.rb` file

## Achievements
- Remove the unneccesary `:source` attribute from our `Item` class ✅ 
- Remove the unneccesary `:source` methods and display messages from our `app` & `main` files✅
- Implement required changes on specific tables in `Schema.sql` file✅
- Implement required changes in `Item.rb` file✅

2023-08-18 08:46 UTC, peterrobert commented on classes/item.rb
> +
This change has been done well

2023-08-18 08:46 UTC, peterrobert commented on main.rb
> +    puts "5. - List all authors (e.g. 'Stephen King')"
This change has been done well

2023-08-18 08:48 UTC, peterrobert commented on classes/item.rb
> +
this change has been done well

2023-08-18 08:53 UTC, peterrobert commented on schema.sql
> +);
This change has been done well

2023-08-18 08:54 UTC, peterrobert approved these changes
Hi @gisachris, 


### Highlights!

[ ] Good feature branch name ✔️
[ ] Descriptive pull request ✔️


Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread or tag me @peterrobert if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-18 09:03 UTC, merged